server:
  port: 8080

spring:
  application:
    name: final_project
  datasource:
    url: "jdbc:postgresql://localhost:5432/project"
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600s
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: file-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      compression-type: gzip
    properties:
      spring.json.trusted.packages: "*"
      max.request.size: 5242880
      buffer.memory: 5242880
file:
  dir: uploads
jwt:
  secret_key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  time-to-live-access-token: 600
  time-to-live-refresh-token: 3600
  issuer: Project
logging:
  level:
    liquibase: INFO
    org.springframework: INFO
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
topics:
  get-file-reply: get-file-reply
  get-email-reply: get-email-reply
  delete-file-request: delete-file-request
  file-responses: file-responses
  file-events: file-events
  get-file-request: get-file-request
  file-answers: file-answers
  email-request: email-request
  get-email: get-email

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metrics
  prometheus:
    metrics:
      export:
        enabled: true

metrics:
  error-metric: error_metric
  kafka-error-metric: kafka_error_metric